### ISSUE TITLE
この issue を閉じる

### ISSUE THREAD

**Issue by ryos36** [iBou-project/OpeniBou#4]
この issue を勇気を持って(笑)閉じる(closeする)

この issue (課題) の担当は @mitchi-0719 にしてあります。
右下のボタンに close issue というのがあるので

Write のところになにかコメントを書いて close issue を押してみましょう。issue が終了します。

これは課題を共有して情報交換して最終的には閉じるというシステムで
issue 管理と呼ばれているものです。
このシステムを使うことによって、課題の対応漏れ等をなくすことが目的です。

**Comment by mitchi-0719** [comment]
closeします
